---
- name: Deploy Root Login service
  hosts: all
  become: true

  tasks:
    - name: Copy systemd service file
      copy:
        src: rootlogin_alert.service
        dest: /etc/systemd/system/rootlogin_alert.service
        mode: "644"

    - name: Ensure /opt/rootlogin_alert directory exist
      file:
        name: /opt/rootlogin_alert
        state: directory
        mode: "755"

    - name: Copy main script to remote server
      copy:
        src: scripts/ssh-login-monitor.sh
        dest: /opt/rootlogin_alert/ssh-login-monitor.sh
        mode: "755"

    - name: Start and enable Root Login service
      systemd:
        name: rootlogin_alert
        state: started
        enabled: true
        daemon_reload: true
